#!/usr/bin/env bash

# OpenSSL requires the port number.
SERVER=$1
SERVERNAME=$(echo $SERVER | sed 's/:.*//')
DELAY=1
ciphers=$(openssl ciphers 'ALL:eNULL' | sed -e 's/:/ /g')

echo Obtaining cipher list from $(openssl version).

for cipher in ${ciphers[@]}
do
echo -n Testing $cipher...
result=$(echo -n | openssl s_client -cipher "$cipher" -connect $SERVER 2>&1)
if [[ "$result" =~ ":error:" ]] ; then
  error=$(echo -n $result | cut -d':' -f6)
  echo NO \($error\)
else
  if [[ "$result" =~ "Cipher is ${cipher}" || "$result" =~ "Cipher    :" ]] ; then
    echo YES
    echo DOWNLOADING CERT
    $(echo -n | openssl s_client -showcerts -servername $SERVERNAME -connect $SERVER -cipher ${cipher} 2>&1 | openssl x509 -outform PEM > ${cipher}.pem)
  else
    echo UNKNOWN RESPONSE
    echo $result
  fi
fi
sleep $DELAY
done
